openapi: 3.0.1
info:
  title: Book Shop
  description: Book CRUD API.
  version: 1.0.0
servers:
- url: /v2
paths:
  /bundle:
    get:
      summary: Get Bundles
      description: get all bundles
      operationId: getAllBundle
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BundleDto'
        400:
          description: Invalid status value
    post:
      summary: Add a Bundle
      operationId: addBundle
      requestBody:
        description: Bundle to be added in shop
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BundleDto'
        required: true
      responses:
        200:
          description: Bundle Added
          content:
            application/json:
              schema:
                type: string
        405:
          description: Invalid input
      x-codegen-request-body-name: book
components:
  schemas:
    BundleDto:
      type: object
      properties:
        id:
          type: string
          example: B0001
        nameGroup:
          type: string
          example: Chả
        name:
          type: string
          example: Chả lụa
        status:
          type: boolean
