server:
  port : 8082
  servlet:
    context-path: /catalog-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OnePos
    username: postgres
    password: 1122288
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        id:
          new_generator_mappings: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  devtools:
    add-properties: true